### ISSUE TITLE
all known related items

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#200]
the spacing is off. sometimes there are double spaces when they should be single spaces. sometimes there are no spaces when they need to be single spaces

**Comment by foxm** [comment]
here's the xsl for these. it's got a bunch of extra stuff for the current site, so it'll need to be tweaked.







[xslforworkinfo.zip](https://github.com/blakearchive/archive/files/249414/xslforworkinfo.zip)

**Comment by queryluke** [comment]
@foxm So this is either a data import issue or I'll need more info. Can you provide an example work? And which related item(s) isn't displaying correctly.

There are 2 possible issues. If you mean extra space as vertical space between the related items, then that can be fixed purely with css.

But if this is something different (i.e., incorrect spacing within the work info), then it's a data import problem. Open up the console on a work page, and look through the returned object. Expand the **related_works** array. Each of these js-ojects represents an item in the related works list.

The code renders the title (if it's a copy, it creates a link to that copy). Then renders the html found in the **info** variable of that js-object. So you can look at the **info** var and see what's there. If there is bad html in **info** this this is a data import issue.

**Comment by joeafletch** [comment]
@queryluke Upon closer inspection, it looks like all italicized, internally-linked titles are not showing up on the redesigned site, leaving an extra blank vertical space. Compare the lists for _America_: on the [current site](http://www.blakearchive.org/exist/blake/archive/work.xq?workid=america&java=no), Deaths Door (right-hand column) shows up as linkable twice, though it's missing on the [redesign](http://c48b4cfd.ngrok.io/blake/work/america). But there also seems to be extra vertical spaces in other instances as well, as in the extra space between the first two entries for _America_--copies C and D. Mike thinks this might be due to the way that the entries are entered in the info file:
![screen shot 2016-05-16 at 1 40 28 pm](https://cloud.githubusercontent.com/assets/13888788/15298129/d7fc8d16-1b6b-11e6-8c9b-87d7ca5d873c.png)
You can see that between copies C and D the </relationship> tag is on its own line, while it's not between copies D and E (and hence no extra space between copies D and E).

In general, any italicized text is not getting rendered in these lists on the redesign. Also, sometimes a line gets broken at a comma--see the "Blake's Notebook, pages 71, 75" entry for _America_ as an example of this.

**Comment by foxm** [comment]
yeah, could we get the code to ignore newlines in the data such as the one between Massachusetts and </relationship>?

**Comment by queryluke** [comment]
Passing this to Nathan, as it's his python scripts that parse the file.

**Comment by nathan-rice** [comment]
This turned out to be an error in the angular template that renders the related work info json.

Fixed.

**Comment by foxm** [comment]
There's still an issue here. The \<link\> tags from the work info for letters and possibly other works aren't getting rendered properly under All Known Related Items.

**Comment by nathan-rice** [comment]
Works referenced in "all related works" are now properly linked to.
