### ISSUE TITLE
Merge relatedness CSV documents

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#251]

**Comment by nathan-rice** [comment]
@joeafletch This looks like an easy change (in terms of the import script) so go ahead and merge these two documents and close this issue once you've updated the blake-relations.csv document and pushed the change, and I'll update the import script to accommodate it.

**Comment by joeafletch** [comment]
@nathan-rice Okay, Nathan, I've merged the two documents and significantly edited the blake-relations.csv (which I've sent in a separate email to you, since GitHub won't let me attach a csv):

1. I've re-titled Column F "related-same production sequence ids" (formerly "related ids") and moved several objects that were erroneously placed here into the new Column G, "related-similar design ids." This column used to be the second column of the "same_motif.csv" and it too has been significantly altered from its former state.

2. Column H is also new and represents our fourth category of relatedness, textual reference. This will operate as another tab on the site, exactly like the same production sequence and similar design (same motif) tabs. The only difference is that this column contains object, copy, and work IDs, since in some cases an object (say a letter) will refer to an entire copy or an entire work, but not a specific object, and we would like users to be able to access--via a handprint--either the referred-to copy or work page in those instances. I realize that this is an exception to the object-object nature of this relational table, but the object, copy, and work IDs are distinct in that object IDs have 3 periods in their titles, copies have 1, and works have 0. We hope that there is a programmatic way to treat this column as a special case, since this functionality is important to us. The relationships are not designated as 2-way in the table in these special instances, i.e., if one page of a letter references an entire work, we want users to be able to get to the work via a references tab, but we don't want to have that page of the letter show up in a references tab for every object of every copy of that particular work.

3. Column G is also new, but you can ignore it for your purposes. These are the objects that are either inscriptions or supplemental views, and as we discussed, the BADs themselves have been modified to point to these.

**Comment by nathan-rice** [comment]
The combination of work, copy and object into one column is bad design.  Now wherever the blake_relations.csv document goes a note has to go along with it that the specified column contains entities of multiple types, and how they should be distinguished.  Additionally, because that column contains complex data, I would need to pre-process the spreadsheet to break the data up into simple components.

I'll implement all the machinery to handle the new feature, but please split textual relatedness into 3 separate columns in the document.

**Comment by joeafletch** [comment]
@nathan-rice Done. I've sent the updated csv as an email attachment to you.

**Comment by nathan-rice** [comment]
Done.

**Comment by foxm** [comment]
i'm still seeing same_motif.csv being processed in import.py. all relations are specified in blake-relations.csv now

**Comment by nathan-rice** [comment]
It is loaded, but not used.

I'm actually in the process of significantly rewriting the import.py script to clean up and simplify it.
