### ISSUE TITLE
object & copy sorting

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#262]
letter handprints on workinfo are now sorted properly by compdate[@value], but they'll have to be sorted again the same way when we implement nextLetter and previousLetter in the object view unless we sort them once correctly during the import

**Comment by nathan-rice** [comment]
It isn't strictly necessary to change the import script, we can change the sort order via SQL query.

Tell me if this ordering for objects is sufficient:

* First, sort by composition date
* Next, sort by object group
* Finally, sort by object number

**Comment by foxm** [comment]
Correct me if I'm wrong, @joeafletch, but the ordering depends on the type of set. Virtual group objects should be sorted by Butlin number and each object should be given an Object number (1, 2, 3...) according to that Butlin sequence. Have a look at issue #261. For letters, objects should be sorted by compdate[@value], which has an order built into it (i.e. 1800.A, 1800.B). Each object within a single letter, yes, should be sorted by object number. For all other types of sets, such as illuminated books), objects should be sorted by copy (either A, B, C... or 1, 2, 3...), and they are. It's just the letters and the virtual groups that are off.

**Comment by joeafletch** [comment]
That all sounds right, but I found one exception among the virtual groups: the [large color printed drawings](http://www.blakearchive.org/exist/blake/archive/vgroup.xq?id=cpd&java=no&titles=&landing=object&mode=vcopy) are sorted alphabetically and not according to Butlin number or compdate. I'm not sure what prompted the editors to order them this way--we can ask Joe V. at the meeting tomorrow morning. Perhaps they'll be willing to allow this group to be sorted according to Butlin number like the other virtual groups.

**Comment by queryluke** [comment]
As it stands now, the Object numbers for virtual groups are set programmatically in the javascript, main.js line 736, via the numberVirtualWorkObjects() function.

I don't know if it has changed, but before, all objects in a virtual group had full_object_id = 1.

**Comment by joeafletch** [comment]
To complicate matters further, we need to differentiate between printdate value and compdate value. For all works that were printed (like illuminated books), we sort by printdate value, and not compdate value. (Letters don't have a printdate, so we default to compdate.) So, slightly amending what Mike wrote above, for illuminated books we order not alphabetically by copy but rather by printdate value--see the [_Songs_ order of copies](http://www.blakearchive.org/exist/blake/archive/work.xq?workid=songsie&java=no) for example. And the letters are a virtual work, but Mike rightly points out the need to sort them by compdate value.

So I think the hierarchy can go as follows:

Non-virtual works:
Printdate value
(If no printdate value) Compdate value

Virtual works:
Butlin number [*once we hear from the editors about the color printed drawings]
* Except for letters, which should be sorted by compdate value

**Comment by queryluke** [comment]
Discussed in meeting 7/13, the following order hierarchy should suffice:

Print Date
Comp Date
Object Number (based on Butlin or Bentley)

@nathan-rice, you mentioned you'd order the virtual group objects during import, correct? Passing the issue your way.

**Comment by foxm** [comment]
i put in some code on the front end to fix some of these sorting issues that will have to be rolled back after the changes are made so the sql queries to avoid redundancy

**Comment by nathan-rice** [comment]
I should note that the BlakeDataService getObjectsForCopy method now returns results sorted as specified.  If there are other BlakeDataService methods that should use this sort order, please feel free to let me know and I'll update as needed.

**Comment by queryluke** [comment]
I removed the sorting javascript. So we can approach this from the data service level.

I also removed the numbering scripts. @nathan-rice all the virtual group objects have the full_object_id of 1. Were you going to set those object IDs on the import, or should I keep numbering them via javascript? (Note: supplemental objects should not be numbered)

Additionally, I *think* BlakeDataService method that gets all copies for works needs to have the following hierarchy:

print date,
copy letter

@foxm  can you confirm that?

**Comment by foxm** [comment]
ok, i took out sorting on the front end, but there still seems to be issues with sorting for letters and virtual groups. letters are out of order and now display every object in a letter on the work info page. and virtual groups are out of order and are displaying different views on the work info page. i'm not sure if the extraneous material that's getting displayed is part of this sorting problem.

**Comment by foxm** [comment]
@queryluke, we crossed lines here. i just committed code over yours. you can roll back my changes, except for the changes to the labeling of the handprints. i added object titles and modified the full_object_id.

**Comment by foxm** [comment]
@queryluke nevermind! it looks like the merge worked out. 

and that hierarchy is right i believe.

**Comment by foxm** [comment]
use biblical water colors and letters as guides:

http://www.blakearchive.org/exist/blake/archive/vgroup.xq?id=biblicalwc&java=no&titles=&landing=object&mode=vcopy

http://www.blakearchive.org/exist/blake/archive/vgroup.xq?id=letters&java=no&titles=&landing=object&mode=vcopy

http://localhost:8002/blake/work/biblicalwc

http://localhost:8002/blake/work/letters

**Comment by foxm** [comment]
see #273 and #275 for design

**Comment by queryluke** [comment]
@nathan-rice can you add an order by clause to the postgres query. All I see in the code is
```results = models.BlakeObject.query.all()```

If the objects could somehow be ordered by their desc_id, I don't think we'd need the hierarchy. I just combed through the database, and it looks like it will work.

**Comment by foxm** [comment]
those issues about the full_object_id have to do with the labeling of the handprints. it looks like in assigning numbers to full_object_id, it's getting overwritten. either we put all that labeling info (Object X (Butlin Y)) minus the object title--the title needs to be separate so that it can go on its own line under the handprint--in one variable or we separate out each bit of info into separate variables in the data model. i think it's fine to put it all in one; it just means that the object number needs to be assigned for the groups and not for everything else.

**Comment by nathan-rice** [comment]
That overwriting is my fault, I confused object_number and full_object_id.  Easily fixed.

If that information will never be utilized separately, and the formatting will never change, then it works to store it as a discrete field.  Otherwise it would be better to break it down.

**Comment by foxm** [comment]
ah, thanks. 

yes, i think it's safe to store it as a discrete field

**Comment by nathan-rice** [comment]
Alright.  I've applied the complex object ordering clause to every BlakeDataService method that returns BlakeObjects.  I've also fixed the full_object_id bug.

Copies were already sorted by print date, so hopefully this should let us close out this issue.

**Comment by foxm** [comment]
something is still off, unfortunately. the full_object_id is still missing "Object" and "(Butlin #)" "(Bentley #, Erdman #, Keynes #)". and there's a trailing '1' in the full_object_id.

also, the virtual groups aren't ordered correctly:

http://localhost:8002/blake/work/biblicalwc

they should look like:

http://www.blakearchive.org/exist/blake/archive/vgroup.xq?id=biblicalwc&java=no&titles=&landing=object&mode=vcopy

and the letters seem to be broken now.

**Comment by queryluke** [comment]
@nathan-rice it's lines 308/9 of import.py, but if I change to ```object_id``` the import fails. Just remove these lines entirely?

Also, did you see my question about sorting by BlakeObject.desc_id? I think we can use that instead of the complex sort. But, again, when I tried to change services.py (line 166) to 
```
query = models.BlakeObject.query.order_by(models.BlakeObject.desc_id)
```
it has no effect on the result set

**Comment by foxm** [comment]
not sure if this is useful info, but the objdescid tag contains a bunch of info, including the compdate[#value]. and remember, it's the value attribute of compdate (and I think printdate) that we want to use to sort, not the _value_ (meaning the field value) of the compdate or printdate tag. i know it's confusing. but the value of the value attribute is what we should be using

**Comment by nathan-rice** [comment]
object_id is the primary key column for the blake_object table, and the object numbers are only unique on a per copy basis, that's why it causes the import to barf. I've updated that part of the code.

**Comment by nathan-rice** [comment]
I've updated the BlakeDataService to use desc_id to sort the results of get_objects_for_copy.  Take a look and see if the ordering is acceptable.  Also, let me know if you would like that to be the universal sort order for object retrieval in all circumstances.

**Comment by foxm** [comment]
thanks. getting an error, though:

Traceback (most recent call last):
DEBUG [23687a8e] 	  File "import.py", line 15, in <module>
DEBUG [23687a8e] 	    import titlecase
DEBUG [23687a8e] 	ImportError: No module named titlecase

does titlecase have to do with capitalization of titles? hold off on that--i'm trying to fix the capitalization on the data end

**Comment by nathan-rice** [comment]
titlecase is listed in the requirements.txt, you just need to run pip install -r requirements.txt.

**Comment by foxm** [comment]
ok, getting the error below. but again, i'm fixing capitalization on the data end. i don't think we can do this programmatically because blake titles his objects in strange ways with capitalization all over the place.

Exception:
Traceback (most recent call last):
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/req/req_set.py", line 601, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/req/req_install.py", line 397, in run_egg_info
    self.setup_py, self.name,
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/setuptools/__init__.py", line 14, in <module>
    from setuptools.extension import Extension
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/setuptools/extension.py", line 10, in <module>
    from .dist import _get_unpatched
  File "/Users/michaelfox/Sites/blake/lib/python2.7/site-packages/setuptools/dist.py", line 375
    always_Copy False, build_directory=None, editable=False,
                    ^
SyntaxError: invalid syntax

**Comment by foxm** [comment]
nevermind, i fixed the pip error. that syntax error was my fault. i had done a regex search and replace across a bunch of files and accidentally included those python files

**Comment by foxm** [comment]
the ordering looks correct for virtual groups! but there's one problem. there's a trailing 'Object 1' in the full_object_id. and i can't check the ordering for letters because they're not displaying

**Comment by nathan-rice** [comment]
That trailing object 1 is part of the full object id, the number before that is the object number.  I can strip out the leading object \# part of the full object id for virtual work objects on import if needed.

The letters issue is separate, I briefly checked it, it's a javascript display issue, the correct set of letter objects is being returned from the server.  @queryluke if you're not already working on that I can take a look at it later this afternoon.

**Comment by queryluke** [comment]
Sorry, I've been driving all day and only had a chance to answer emails sporadically. But I can handle it when I get settled.

**Comment by foxm** [comment]
ok, when we display full_object_id, it shows, for example: Object 3Object 1 (Butlin 436), so it seems the whole thing is the full_object_id for the virtual group objects. we want to take out that "Object 1" embedded in all the full_object_ids of the virtual group objects

**Comment by foxm** [comment]
@queryluke i think i fixed the letters problem by modifying multiObjectGroupCopies function below. i guess it might be better to nest these somehow during the import, but for now this'll work

`blakeData.multiObjectGroupCopies = function(objects){
            if(angular.isArray(objects)){
                var objectGroupArray = [];

                angular.forEach(objects, function(obj){
                    //if(obj.object_number == 1){
                    //    objectGroupArray.push(obj);
                    //}
                    if(obj.full_object_id.indexOf("Object 1")){
                        objectGroupArray.push(obj);
                    }
                });

            }
            return objectGroupArray;
        }`

**Comment by foxm** [comment]
actually that doesn't fix them all. i'm stumped on this one

**Comment by queryluke** [comment]
Ok, letters are showing but this is a temporary fix. The way I've approached letter and supp images needs to be refactored. It was a poor decision on my part. I'll get to that monday.

Sadly sorting desc_id does not work with letters. The issue is that all other desc ids contain the object order via a set number of characters. For example:

Non-virtual group, a 2 character number at the end. Sort works fine
```
europe.a.illbk.01
europe.a.illbk.02
europe.a.illbk.03
europe.a.illbk.04
...

Virtual groups, a 3 character number (based on butlin) in the middle (using illus to bible as example)
```
but146.1.wc.01
but435.1.wc.01
but436.1.wc.01
but438.1.wc.01
...
````

But for letters use a date...and a date formatted day/month/year
```
lt10november1825.1.ltr.01
lt14july1826.1.ltr.01
lt14sept1800.1.ltr.02
lt1825.1.ltr.01
lt1april1800.1.ltr.01
```

I'd say we could use logic to parse through this, but as you can see, there are major inconsistencies:
1. Some months are abbreviated
2. Some only have years
3. Days lack leading zeros


A quick solution would be to rename the bads, putting the year first would fix everything. 

But as I type this, I'm thinking, is order by desc id the best approach? What happens when a virtual group is made that combines 2 objects from 2 completely different works? Or, if this is the right approach, should there be more care in creating desc ids? Again I'm thinking of both now but also for longevity.

Thoughts?

**Comment by foxm** [comment]
Quick thought from my phone:

Descid won't work for virtual groups either. The order of Butlin numbers doesn't always correspond with the order of composition dates. Joe f. pointed out exceptions. This arises when joe viscomi corrects Butlin. Could we distinguish non virtual objects from virtual ones from letter objects during the import to fine tune the ordering?  I'm skeptical that there's a good way to universally order everything

**Comment by queryluke** [comment]
What if the objects were sorted in their correct order on the works.csv? This would give editors the power to adjust order as needed, right, just by rearranging the bads in the virtual object column?

**Comment by nathan-rice** [comment]
That is how the objects are currently assigned an object number.  If the editors were responsible for the ordering of virtual works in the works.csv then we could just sort via object number in all cases.

**Comment by queryluke** [comment]
yep object number it looks like object number is the correct way to go. just pushed that change. i'll wait on confirmation form @foxm

**Comment by foxm** [comment]
we could do that, although that means we'll have to adjust the related csv as well. related objects need to be sorted by print date[@value]--which makes me realize that non-virtual works need to be, too, no printdate--then compdate[@value]. it's odd that we can't seem to do the sorting programmatically.

**Comment by foxm** [comment]
object number seems to be ok. i guess if we find a mistake, we'll adjust the works.csv. the only problem i see at the moment is that copies of non-virtual works are being sorted by printdate, not printdate[@value]. i guess since we're doing ordering for objects manually now, we should do it manually for copies, though i still think programmatically would be better

**Comment by queryluke** [comment]
I've order the non-virtual copies by print data value now.

I'm not sure related.csv needs to be ordered according to the same schema as copies and virtual works. The logic is that objects within a copy/vg have a sequential scope. But a group of objects from varying scopes(i.e., works) will not have any related sequential ordering. As such, a standard visible sort order would probably be better, like title, butlin, bentley, etc.

Either way, I think in next week's meeting we should review sorting Joe V.

**Comment by foxm** [comment]
related works have to be sorted by print date, then comp date, as they are on the current site

**Comment by nathan-rice** [comment]
We can apply object number sorting from only certain methods of the BlakeDataService.  Specifically, getObjectsForCopy.  We can apply different sorting rules for getObjectsWithSameMotif/etc.

We can also programmatically deal with some of the sorting issues by sorting the objects being attached to copies on import to ensure the desired object number.

**Comment by foxm** [comment]
yes, we would have to apply different ordering to the related tabs. i still think we should do everything programmatically because now it seems like we're going to have a combination of manual and programmatic sorting

**Comment by nathan-rice** [comment]
I'll all for programmatic sorting, but I'd rather have the original data reflect the correct order when possible, rather than having a special set of sorting clauses for letters vs biblical watercolors vs several other things.  The correct sort order is a form of knowledge, and it is always best to incorporate knowledge as early in the pipeline as possible, unless there is a big gain in efficiency from doing it later.  Additionally, having the source data reflect the source data gives the editors control, if it is in the code, then any changes have to go through a programmer, and involve server re-deployment.

**Comment by foxm** [comment]
the gain--and maybe it's not a big gain--is elimination of human error. they don't need control over the ordering. after it's done right, there's never a reason to change it. but they often make mistakes.

**Comment by nathan-rice** [comment]
I agree avoiding human error is a plus, I think the best solution is to come up with a universal sorting scheme that works for **almost** everything, then include a final clause in that scheme that is a "fallback" which is determined manually in the special cases.  That avoids any special case code and also limits the amount of human work/potential for error.

I think that the object_number is a good candidate field for this purpose.

**Comment by foxm** [comment]
ok, it's just that technically speaking object_number ordering is pre-determined manually (i.e. during the making of the BAD) by looking at printdate[@value]. it's true, though, that the editors rarely make a mistake with that process.

**Comment by foxm** [comment]
ok, so for now i think we just need to correct the programmatic non-virtual copy ordering. it should be ordered by printdate[@value], not printdate

**Comment by queryluke** [comment]
I've just pushed the branch [sorting](https://github.com/blakearchive/archive/tree/sorting). It does the following:

Copy Model, now has 6 attributes relating to date:
- print_date_value (string from the ```value="..."``` attribute on the ```<printdate>``` element)
- print_date (int parsed from **print_date_value**)
- print_date_string (string between ```<printdate>...</printdate>```)

(repeat this logic for **compdate**)

The Object Model now has 4 attributes relating to date, mapped from the above
- copy_print_date
- copy_print_date_value
- copy_composition_date
- copy_composition_date_value

Copies within works are sorted by:
**print_date_value** > **composition_date_value**

Objects (everywhere) are sorted by:
**copy_print_date_value** > **copy_composition_date_value** > **object_number**

I think should at least give us a starting point. Note that is should also remedy #291, and provide the necessary data for #290

**Comment by foxm** [comment]
@queryluke  very nice, luke! thank you! i verified that non-virtual, virtual, and letter copies and objects are sorted correctly. doing this programmatically, as it is now, is much more preferable. and at first glance, i can say it does remedy #291. i'll fix #290. i'm going to leave this open for a day or two, just to make sure i haven't missed anything.

**Comment by foxm** [comment]
@queryluke actually, it looks like we'll need the copy_print_date_string and copy_composition_date_string in the Object model as well. those should contain everything within the tags but before <note>. not sure if they include the string in <note> right now

**Comment by nathan-rice** [comment]
It probably isn't necessary to copy those fields, you just need to do a join on any blake_object queries with blake_copy.  If you let me know where/how copy_print_date_string and copy_composition_date_string need to be accessed I can update the BlakeDataService to supply them in the appropriate manner.

**Comment by foxm** [comment]
i need to access them from the Object model. they should be the same as `copy.source.objinfo.printdate['#text']` and `copy.source.objinfo.compdate['#text']`

**Comment by foxm** [comment]
and i need to access all of those print date and comp date variations from the Work Model, too, for labeling purposes

**Comment by foxm** [comment]
hold off on my last two comments. i've gotten most of the labeling correct. the only thing that i can't seem to access is `obj.source.objinfo.printdate['#text']` and `obj.source.objdescid.compdate['#text']` from the objectsfromsame tab. @queryluke it looks like the "source" field is null for objects under objectsfromsame. would you mind looking into this? the code is in place to grab the values of those fields for labeling the objects under objectsfromsame.

**Comment by queryluke** [comment]
source is a pretty hefty field. If all you want is the comp/print data string then we'll just make those available. I've just pushed an update to the object model. copy_composition/print_date_string is available.

Nathan, however you want to optimize the python is fine, so long as all 6 strings are available in the json returns.

**Comment by foxm** [comment]
ok, the strings are fine for now. but at the moment they contain the text within the \<note\> elements within the compdate and printdate elements--don't know if you saw my comment to your commit. they should include everything up to the \<note\> element

**Comment by queryluke** [comment]
closing this, since the overall issue (sorting) is complete. We can address the note issue is a different issue
